name: Setup
description: Setup Bun and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        no-cache: true

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
