name: Check CLang

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check-clang.yml'
      - 'ios/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check-clang.yml'
      - 'ios/**'

jobs:
  CLang-Format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: brew install clang-format
      - name: Check ios clang formatting
        run: |
          ./scripts/format-ios.sh
      - name: Check for changes
        run: git diff --exit-code HEAD
